# Generated by Django 4.2 on 2024-01-17 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Login', '0011_trialperiod'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttermsupdates',
            name='interested_to_continue',
            field=models.BooleanField(default=0),
        ),
    ]
