# Generated by Django 3.2.25 on 2024-05-14 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0002_transportation_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='retainerinvoice',
            name='adjustment',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='retainerinvoice',
            name='paid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
